[package]
name = "alloy-contract-interact"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.41", features = ["full", "node-bindings"] }
tokio = { version = "1.48.0", features = ["full"] }
